spring:
    config:
        import:
            env.properties
    datasource:
        hikari:
            connection-timeout: '200000'
            max-lifetime: '1800000'
        password: ${DB_PASSWORD}
        username: ${DB_USER}
        url: jdbc:postgresql://${DB_URL}