spring:
    datasource:
        hikari:
            connection-timeout: '200000'
            maximum-pool-size: '5'
            max-lifetime: '1800000'
        password: <Password> # the password should not be commited 
        username: <Username>
        url: <DatabaseUrl>
