spring:
    datasource:
        hikari:
            connection-timeout: '200000'
            maximum-pool-size: '5'
        password: SteinIsTheKey
        username: h594760
        url: jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5432/h594760